scala-doc:
	open https://docs.scala-lang.org/getting-started/index.html
	open https://docs.scala-lang.org/tour/tour-of-scala.html
	open https://docs.scala-lang.org/cheatsheets/index.html

spark-doc:
	open https://spark.apache.org/docs/latest/sql-programming-guide.html

link-data:
	ln -s "$(PWD)/../data" "$(PWD)/src/main/resources/data"